MVCStudentManager-v0.0.7/MVCStudentManager/MVCStudentManager/Controllers/HocSinhController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCStudentManager.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;

namespace MVCStudentManager.Controllers
{
    public class HocSinhController : Controller
    {
        dbStudentManagerDataContext db = new dbStudentManagerDataContext();
        // GET: HocSinh
        public ActionResult Index()
        {
            return View();
        }
        // Trang học sinh
        public ActionResult Student(int ? page, string searchString)
        {
            var hocsinh = from e in db.HocSinhs select e;
            if (!String.IsNullOrEmpty(searchString))
            {
                hocsinh = hocsinh.Where(s => s.HoTen.Contains(searchString));
            }
            ViewBag.SeachString = searchString;
            int pageNumber = (page ?? 1);
            int pageSize = 7;
            return View(hocsinh.ToList().OrderBy(n => n.MaHS).ToPagedList(pageNumber, pageSize));
        }

        // Trang lớp
        public ActionResult Class(int? page, string searchString)
        {
            var lop = from e in db.Lops select e;
            if (!String.IsNullOrEmpty(searchString))
            {
                lop = lop.Where(s => s.TenLop.Contains(searchString));
            }
            ViewBag.SeachString = searchString;
            int pageNumber = (page ?? 1);
            int pageSize = 7;
            return View(lop.ToList().OrderBy(n => n.MaLop).ToPagedList(pageNumber, pageSize));
        }

        // Trang điểm
        public ActionResult Mark(int? page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 7;
            return View(db.DiemMons.ToList().OrderBy(n => n.MaDiemMon).ToPagedList(pageNumber, pageSize));
        }
    }
}

MVCStudentManager-v0.0.7/MVCStudentManager/MVCStudentManager/Views/HocSinh/Class.cshtml
@using MVCStudentManager.Models
@using PagedList.Mvc;
@model PagedList.PagedList<MVCStudentManager.Models.Lop>
@{
    /**/

    /**/

    ViewBag.Title = "Class";
    Layout = "~/Views/Shared/_LayoutHS.cshtml";
}

<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- search form (Optional) -->
        <h4 style="text-align:center; color:whitesmoke; font-weight:bold">Tìm theo tên</h4>
        <form action="#" method="get" class="sidebar-form">

            <div class="input-group">
                @using (Html.BeginForm("Class", "HocSinh", FormMethod.Get, new { @class = "navbar-form navbar-right", role = "search", id = "search-form", onsubmit = "return empty();" }))
                {
                    @*<input type="text" name="q" class="form-control" placeholder="Search...">*@
                    <input type="text" id="SearchString" name="SearchString" value="" style="width: 170px;" class="form-control" placeholder="Search...">
                    @*@Html.TextBox("SearchString")*@
                    <span class="input-group-btn">
                        <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                    @*<p style="text-align:center">
                            @Html.TextBox("SearchString")
                        </p>
                        <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                            <i class="fa fa-search"></i>
                        </button>*@
                }
            </div>
        </form>
        <!-- /.search form -->
        <!-- Sidebar Menu -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header" style="text-align:center">
                <h4 style="color:whitesmoke;font-weight:bold">MENU</h4>
            </li>
            <!-- Optionally, you can add icons to the links -->
            <li>
                <a href="@Url.Action("Student","HocSinh")">
                    <i class="fa fa-link"></i>
                    <span>Xem danh sách học sinh</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Class","HocSinh")">
                    <i class="fa fa-link"></i>
                    <span>Xem danh sách lớp</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Mark","HocSinh")">
                    <i class="fa fa-link"></i>
                    <span>Xem điểm</span>
                </a>
            </li>
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>

<br>
<h1 style="text-align:center;font-weight:bold">Danh sách lớp</h1>

<table class="table">
    <tr>
        <th style="width:100px">Lớp</th>
        <th style="width:200px">Khối</th>
        <th style="width:200px">Năm học</th>
        <th style="width:200px">Giáo viên</th>
        <th style="width:200px">Sỉ số</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenLop)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Khoi.TenKhoi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NamHoc.TenNamHoc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GiaoVien.TenGiaoVien)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SiSo)
            </td>
        </tr>
    }
</table>
Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("Class", new { page = page }))
</div>
<style>
    .MenuTrang li {
        display: inline;
    }
</style>

MVCStudentManager-v0.0.7/MVCStudentManager/MVCStudentManager/Views/HocSinh/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutHS.cshtml";
}

<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- search form (Optional) -->
        <h4 style="text-align:center; color:whitesmoke; font-weight:bold">Tìm theo tên</h4>
        <form action="#" method="get" class="sidebar-form">

            <div class="input-group">
                @using (Html.BeginForm("", "", FormMethod.Get, new { @class = "navbar-form navbar-right", role = "search", id = "search-form", onsubmit = "return empty();" }))
                {
                    @*<input type="text" name="q" class="form-control" placeholder="Search...">*@
                    <input type="text" id="SearchString" name="SearchString" value="" style="width: 170px;" class="form-control" placeholder="Search...">
                    @*@Html.TextBox("SearchString")*@
                    <span class="input-group-btn">
                        <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                    @*<p style="text-align:center">
                            @Html.TextBox("SearchString")
                        </p>
                        <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                            <i class="fa fa-search"></i>
                        </button>*@
                }
            </div>
        </form>
        <!-- /.search form -->
        <!-- Sidebar Menu -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header" style="text-align:center">
                <h4 style="color:whitesmoke;font-weight:bold">MENU</h4>
            </li>
            <!-- Optionally, you can add icons to the links -->
            <li>
                <a href="@Url.Action("Student","HocSinh")">
                    <i class="fa fa-link"></i>
                    <span>Xem danh sách học sinh</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Class","HocSinh")">
                    <i class="fa fa-link"></i>
                    <span>Xem danh sách lớp</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Mark","HocSinh")">
                    <i class="fa fa-link"></i>
                    <span>Xem điểm</span>
                </a>
            </li>
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>

<h2 style="text-align:center; color:firebrick"><strong>Trường Trung Học Phổ Thông HUFLIT</strong></h2>
<p style="text-align:center">
    <img src="~/images/gioithieutruong.jpg" />
</p>

<p style="font-weight: bold;text-align: center;font-style: italic;"></p>

<strong>
    <div class="bodytext">
        <div style="text-align: justify;">
            <div>
                &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Trên cơ sở tiền thân là Trường Dân lập Ngoại ngữ và Tin học Sài Gòn được thành lập theo quyết định số 871/QĐ-UB ngày 02/6/1992 của UBND TP. HCM thực hiện sứ mệnh đào tạo nguồn nhân lực thời mở cửa và hội nhập quốc tế, khu vực hóa và toàn cầu hóa, ngày 26/10/1994 Thủ tướng Chính phủ Võ Văn Kiệt ký Quyết định số 616/TTg chính thức phát triển Trường Dân lập Ngoại ngữ và Tin học Sài Gòn thành Trường Đại học Ngoại ngữ - Tin học TP. HCM (Ho Chi Minh City University of Foreign Languages and Information Technology - HUFLIT). Đây là trường đại học dân lập đầu tiên ở TP. HCM và khu vực phía Nam. Đến năm 2015, Trường chính thức được chuyển đổi loại hình đào tạo từ trường đại học dân lập sang loại hình trường đại học tư thục theo Quyết định số 1757/QĐ-TTg ngày 15/10/2015 của Thủ tướng Chính phủ. Trải qua hơn 25 năm phát triển, với mục tiêu “không vì lợi nhuận” và phương châm đào tạo lực lượng cử nhân chất lượng cao, thành thạo chuyên môn và bảo đảm các kỹ năng cần thiết đáp ứng nhu cầu thị trường lao động, Trường Đại học Ngoại ngữ - Tin học TP. HCM đã không ngừng nỗ lực phát triển và trở thành một trong những trường đại học có uy tín và chất lượng cao, được xã hội công nhận, đóng góp tích cực, hiệu quả vào sự nghiệp xã hội hóa giáo dục, công cuộc xây dựng và phát triển đất nước.<br />
                &nbsp;
            </div>
            &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Phấn đấu thực hiện thành công mục tiêu và sứ mệnh đào tạo của Trường, HUFLIT ngoài việc không ngừng cải tiến chương trình đào tạo, phương pháp giảng dạy, hệ thống quản lý, trường còn luôn tích cực chủ động hội nhập khu vực và quốc tế trong lĩnh vực đào tạo ngay từ khi mới thành lập thông qua các hoạt động hữu nghị và ngoại giao nhân dân. Cho đến nay, HUFLIT đã ký kết hơn 80 văn bản hợp tác với các cơ sở đào tạo và tổ chức giáo dục trên thế giới, tạo điều kiện để cán bộ, giảng viên và sinh viên có cơ hội tiếp cận, trải nghiệm môi trường học tập và chương tình đào tạo của các nước qua các chương trình hợp tác học thuật, du học, trao đổi giảng viên và sinh viên.<br />
            <br />
        </div>
    </div>
</strong>

MVCStudentManager-v0.0.7/MVCStudentManager/MVCStudentManager/Views/HocSinh/Mark.cshtml
@using MVCStudentManager.Models
@using PagedList.Mvc;
@model PagedList.PagedList<MVCStudentManager.Models.DiemMon>

@{
    ViewBag.Title = "Mark";
    Layout = "~/Views/Shared/_LayoutHS.cshtml";
}

<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- search form (Optional) -->
        <h4 style="text-align:center; color:whitesmoke; font-weight:bold">Tìm theo tên</h4>
        <form action="#" method="get" class="sidebar-form">

            <div class="input-group">
                @using (Html.BeginForm("", "", FormMethod.Get, new { @class = "navbar-form navbar-right", role = "search", id = "search-form", onsubmit = "return empty();" }))
                {
                    @*<input type="text" name="q" class="form-control" placeholder="Search...">*@
                    <input type="text" id="SearchString" name="SearchString" value="" style="width: 170px;" class="form-control" placeholder="Search...">
                    @*@Html.TextBox("SearchString")*@
                    <span class="input-group-btn">
                        <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                    @*<p style="text-align:center">
                            @Html.TextBox("SearchString")
                        </p>
                        <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                            <i class="fa fa-search"></i>
                        </button>*@
                }
            </div>
        </form>
        <!-- /.search form -->
        <!-- Sidebar Menu -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header" style="text-align:center">
                <h4 style="color:whitesmoke;font-weight:bold">MENU</h4>
            </li>
            <!-- Optionally, you can add icons to the links -->
            <li>
                <a href="@Url.Action("Student","HocSinh")">
                    <i class="fa fa-link"></i>
                    <span>Xem danh sách học sinh</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Class","HocSinh")">
                    <i class="fa fa-link"></i>
                    <span>Xem danh sách lớp</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Mark","HocSinh")">
                    <i class="fa fa-link"></i>
                    <span>Xem điểm</span>
                </a>
            </li>
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>

<br>
<h1 style="text-align:center;font-weight:bold">Danh sách Điểm</h1>

<table class="table">
    <tr>
        <th style="width:100px">Học kì</th>
        <th style="width:200px">Học sinh</th>
        <th style="width:200px">Môn học</th>
        <th style="width:200px">Điểm 15 phút</th>
        <th style="width:200px">Điểm 1 tiết</th>
        <th style="width:200px">Điểm 1 học kỳ</th>
        <th style="width:200px">Điểm trung bình</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.HocKy.TenHocKy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HocSinh.HoTen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MonHoc.TenMon)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Diem15phut)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Diem1Tiet)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiemHK)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiemTB)
            </td>
        </tr>
    }
</table>
Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("Student", new { page = page }))
</div>
<style>

    .MenuTrang li {
        display: inline;
    }
</style>

MVCStudentManager-v0.0.7/MVCStudentManager/MVCStudentManager/Views/HocSinh/Student.cshtml
@using MVCStudentManager.Models
@using PagedList.Mvc;
@model PagedList.PagedList<MVCStudentManager.Models.HocSinh>
@{
    ViewBag.Title = "Student";
    Layout = "~/Views/Shared/_LayoutHS.cshtml";
}

<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- search form (Optional) -->
        <h4 style="text-align:center; color:whitesmoke; font-weight:bold">Tìm theo tên</h4>
        <form action="#" method="get" class="sidebar-form">

            <div class="input-group">
                @using (Html.BeginForm("Student", "HocSinh", FormMethod.Get, new { @class = "navbar-form navbar-right", role = "search", id = "search-form", onsubmit = "return empty();" }))
                {
                    @*<input type="text" name="q" class="form-control" placeholder="Search...">*@
                    <input type="text" id="SearchString" name="SearchString" value="" style="width: 170px;" class="form-control" placeholder="Search...">
                    @*@Html.TextBox("SearchString")*@
                    <span class="input-group-btn">
                        <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                    @*<p style="text-align:center">
                            @Html.TextBox("SearchString")
                        </p>
                        <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                            <i class="fa fa-search"></i>
                        </button>*@
                }
            </div>
        </form>
        <!-- /.search form -->
        <!-- Sidebar Menu -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header" style="text-align:center">
                <h4 style="color:whitesmoke;font-weight:bold">MENU</h4>
            </li>
            <!-- Optionally, you can add icons to the links -->
            <li>
                <a href="@Url.Action("Student","HocSinh")">
                    <i class="fa fa-link"></i>
                    <span>Xem danh sách học sinh</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Class","HocSinh")">
                    <i class="fa fa-link"></i>
                    <span>Xem danh sách lớp</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Mark","HocSinh")">
                    <i class="fa fa-link"></i>
                    <span>Xem điểm</span>
                </a>
            </li>
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>

<br>
<h1 style="text-align:center;font-weight:bold">Danh sách học sinh</h1>

<table class="table">
    <tr>
        <th style="width:200px">Họ tên</th>
        <th style="width:200px">Ngày sinh</th>
        <th style="width:100px">Giới tính</th>
        <th style="width:200px">Email</th>
        <th style="width:200px">Địa chỉ</th>
        <th style="width:200px">Tên lớp</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.HoTen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgaySinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GioiTinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaChi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lop.TenLop)
            </td>
        </tr>
    }
</table>

Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("Student", new { page = page }))
</div>
<style>
    .MenuTrang li {
        display: inline;
    }
</style>